### ISSUE TITLE
Supporting HTTPS

### ISSUE THREAD

**Issue by jaredbroad** [sukona/Grapevine#105]
Please extend Grapevine to support HTTPS.

**Comment by scottoffen** [comment]
You can already use whatever protocol HttpListener supports (HTTP and HTTPS). From this perspective, even earlier versions of Grapevine should work with HTTPS by simply setting the server protocol:

```csharp
server.Protocol = "https";
```
> See the [relevant code in Grapevine](https://github.com/sukona/Grapevine/blob/master/src/Grapevine/Server/ServerSettings.cs#L68)

While there is very little to do in your code, there is more that will need to be done on the machine the server is running on for this to work.
- See [the HttpListener docs](https://msdn.microsoft.com/en-us/library/system.net.httplistener(v=vs.110).aspx), especially the notes at the bottom of the page.
- There is an excellent [writeup on StackOverflow](http://stackoverflow.com/questions/11403333/httplistener-with-https-support)
- If you run into [problems like this one](http://stackoverflow.com/a/34726938), I would suggest searching on StackOverflow, as the issue will have nothing to do with Grapevine, and everything to do with the certificate setup.

Please let me know if these steps don't work for you, or if you discover additional steps are necessary.

**Comment by richardcurteis** [comment]
I have a solution working for this now.
Bound a certificate to 8443 on Windows 10 and configured `RESTServer `as below.

```
var server = new RESTServer
            {
                Host = Configuration.Config.Get("grapevine-host", "localhost"),
                Port = Configuration.Config.Get("grapevine-port", "8443"),
                Protocol = Configuration.Config.Get("grapevine-protocol", "https")
            };
```

**Comment by jaredbroad** [comment]
Thank you @scottoffen
