### ISSUE TITLE
HttpWebRequest initialised with null CookieContainer

### ISSUE THREAD

**Issue by elpht** [sukona/Grapevine#107]
In AdvancedRestRequest, method with signature _internal HttpWebRequest ToHttpWebRequest(UriBuilder builder)_ there is no initialisation of _HttpWebRequest.CookieContainer_. This container is used later on when _RestClients_ executes a _RestRequest_ through method _Execute_

**Comment by scottoffen** [comment]
This was a defect I fixed in earlier versions that I overlooked when updating everything for version 4. thanks for catching this. I'll have an updated nuget up shortly.

**Comment by scottoffen** [comment]
There's an updated nuget to fix this, version 4.0.0.79

**Comment by elpht** [comment]
Thanks for your great job!
