### ISSUE TITLE
Dual-licensed under MIT

### ISSUE THREAD

**Issue by seeseekey** [sukona/Grapevine#109]
Hi,

i would ask if it possible is to dual-licence the library under MIT and Apache license (or only MIT-License)?

The reason is the possibility to relicensing the code unter other free licenses. From the MIT licence you can relicensing the code to modified BSD, Apache, LGPL, GPL and AGPL. From the apache license you can relicensing the code only to LGPL 3, GPL3 and AGPL 3.

Sincery,

Florian

**Comment by scottoffen** [comment]
I'll look into this.

**Comment by scottoffen** [comment]
@seeseekey are you talking about using the Grapevine package (e.g. from NuGet) as a dependency for another project/product that would be licenced differently, or using the Grapevine source code to make a derivative work that would potentially have a different licence? I'm trying to figure out how the Apache license would inhibit either of these scenarios.
