### ISSUE TITLE
REST server embedded in auxiliary dll does not load resources

### ISSUE THREAD

**Issue by elpht** [sukona/Grapevine#114]
In case the REST server is embedded in an auxiliary dll, when it starts and routes are loaded, through _IRouter.RegisterAssembly_ method, the entry assembly is always the "root" application but not the helper library where REST server and resources are defined. Result: no resources found, empty route table.

Suggestion: since there is no other initialization of the routing table except in _RestServer.Start_ and that method must be called explicitly from outside, _System.Reflection.Assembly.GetCallingAssembly()_ is returning the desired result at that point. This could be passed as an argument to _IRouter.RegisterAssembly_

**Comment by scottoffen** [comment]
I noticed that as well, There is a fix for this that I'm testing already for the next release. Thanks for logging a ticket to help me keep track of this.

**Comment by elpht** [comment]
Just another interesting solution: http://stackoverflow.com/a/11141255

**Comment by elpht** [comment]
After commit `https://github.com/sukona/Grapevine/commit/e697952e109e7d7233bd4e4ad65260da29c0a93b` it looks like it is solved. It is only missing the registration of routes obtained by Scan method

**Comment by scottoffen** [comment]
Fixed as of commit [73d66f3](https://github.com/sukona/Grapevine/commit/73d66f3df11880de6ef7814bb7728622d0a87aef)
