### ISSUE TITLE
Parsing Content-Type to enum ContentType in RestResponse constructor does not work

### ISSUE THREAD

**Issue by elpht** [sukona/Grapevine#117]
String Content-Type does not match with enum values. Defect code:

[ContentType = (ContentType)Enum.Parse(typeof(ContentType), _response.ContentType);](https://github.com/sukona/Grapevine/blob/master/src/Grapevine/Client/RestResponse.cs#L158)

**Comment by scottoffen** [comment]
I'm going to need a little more information here. What was the content-type value it was trying to parse when you received the error?

**Comment by elpht** [comment]
I am working directly with the source, since I can temporary fix issues and go on with my project, so I have the latest commits. 

Content-type was "application/json", but the thing is you are using Enum.Parse(enumType, valueString) and ContentType enum values (string representation) do not match with what is received from HttpWebResponse. It matches with enum attribute ContentTypeMetadata.Value, what you probably have prepared to map string content-types and enum values.
