### ISSUE TITLE
ContentType is not correctly detected

### ISSUE THREAD

**Issue by SoftExpert** [sukona/Grapevine#129]
Hello,

While testing this excellent framework, I ran into some issues with content type detection.
Upon some introspection, I found the culprit: contentType might come richer than expected (either the mime type followed by the encoding or mime type coming as doubled).

My fix was a one-liner in the ContentType.cs file. Maybe it helps others ...

`public static ContentType FromString(this ContentType ct, string contentType)`
`{`
`    return string.IsNullOrWhiteSpace(contentType)`
`      ? ContentType.DEFAULT`
`//: Enum.GetValues(typeof(ContentType)).Cast<ContentType>().FirstOrDefault(t => t.ToValue().Equals(contentType));`
`  : Enum.GetValues(typeof(ContentType)).Cast<ContentType>().FirstOrDefault(t => contentType.Contains(t.ToValue()));`
`}`

Best regards,
Marian

**Comment by scottoffen** [comment]
Did you want to do a pull request? You've already got the fix in there, just add a unit test and it would be good to go.

**Comment by scottoffen** [comment]
Hmm. Fixing it for the value of `text/html; charset=UTF-8,text/html; charset=windows-1251` took a little more than just your proposed line change.

**Comment by scottoffen** [comment]
I got bored waiting for another build to finish, so I decided to tackle this real quick.

**Comment by SoftExpert** [comment]
Hi,

Sorry for commenting this late, but your solution seems to be prone to further errors: you expect the mimetype to be in the first position in the string; my approach was to search the correct and known mimetype from the collection directly in the string. If found we have a winner, if not we evaluate the next.

What do you think?

Best regards,
Marian

**Comment by scottoffen** [comment]
You are correct in that I am assuming that the mimetype will be in the first position in the string. Can you help me understand under what circumstances this would not be he case?

I suppose there is a possibility of having additional invalid characters in the string (such as extra white-space, perhaps?) but I think the HttpListenerContext already has that stripped out.

**Comment by SoftExpert** [comment]
Hi Scott,

For example a badly configured (or implemented) client application or a testing application which allows to manually compose request's contents.
I fully agree that every application should respect standards but sometimes this is not the case.

And while searching for the most optimal solution, I bet a better approach can be found: being able to specify a subset of the content types should increase the speed with which the detection is performed; also there are faster lookups than string comparison (hash based, for example Dictionary).

What do you think?

Best regards,
Marian

**Comment by scottoffen** [comment]
You mention two specific items in your previous post:

1.  You suggest that if a request or response contains a malformed Content-type HTTP header then then mechanism for matching that value to the `ContentType` enum should attempt to suss it out of the string value provided prior to assigning it the default value.

2. You suggest that there are potentially faster look-up algorithms to use to match the `ContentType` enum than the one currently in use.

While these may be worthy of discussion, I would ask that you open a new ticket for each of them, as each one would be a separate enhancement request. No need to pollute this space with off-topic discussions.

Alternatively - and I would recommend this - ask the question in the [Grapevine Gitter room](https://gitter.im/sukona/Grapevine) and solicit feedback/opinions from the rest of the user base prior to opening a feature request.

**Comment by scottoffen** [comment]
Fails when content type has two values, where the first one has no parameters but the second one has parameters.

```
test/html,text/htm; charset=UTF-8
```
