### ISSUE TITLE
High CPU Usage on Requests

### ISSUE THREAD

**Issue by moelski** [sukona/Grapevine#138]
Hi !

I just compiled the latest GIT release (4.0) and run a very simple console app test (Visual Studio 2015). 
There was only a "Hello World" response (one route). 

If you request data from the Rest server it very often produce high CPU usage. 
The usage is so high that even my VLC mp3 player stops for a short time. 
I use a Core I7 CPU so there should be enough power to handle the load ... 

Anyway ... While whatching the taskmanager I can see peaks from 75-90% CPU load. 

Can you tell me what´s the problem? Any solutions? 

regards Dominik

![cpu load](https://cloud.githubusercontent.com/assets/17078960/19767601/e35c37d8-9c53-11e6-9317-5fa864b1c986.PNG)
Very high CPU usage with very simple routes/responses

**Comment by scottoffen** [comment]
Looking into this

**Comment by moelski** [comment]
Hi !

My test setup is nothing more than this code: 
```
        static void Main(string[] args)
        {
            using (var server = new RestServer())
            {
                server.LogToConsole();
                server.Host = "10.100.12.53";
                server.Port = "80";
                server.Start();
                Console.WriteLine("Server started ...");
                Console.ReadLine();
                server.Stop();
                Console.WriteLine("Server ended ...");
                Console.ReadKey();
            }
        }

namespace RestTest
{
    [RestResource]
    public class TestResource
    {
        [RestRoute]
        public IHttpContext HelloWorld(IHttpContext context)
        {
            context.Response.SendResponse("Hello, world.");
            return context;
        }
    }
}
```
Seperated into one program class and one TestResource class. 
And it doesn´t matter if I use localhost or another IP on my computer. 

I consume the service with a webbrowser (by pressing fast F5) or by Fiddler. 
The problem is that the high CPU usage is not constant. Some times it´s really fast and sometimes it blocks all my 8 Cores. 
And on another computer it runs ok for a while. 

So it´s a little bit hard to determin the problem. 

Hope you can give me a hint or find a bug ...

**Comment by scottoffen** [comment]
Try reducing the number of concurrent threads. It defaults to (50 * `Environment.ProcessorCount`), which may not be ideal for your hardware. It's just an arbitrary number. This code will set it to (5 * `Environment.ProcessorCount`).

```csharp
using (var server = new RestServer {Host="10.100.12.53", Port = "80", Connections = 5})
{
    server.LogToConsole();

    server.Start();
    Console.WriteLine("Server started ...");

    Console.ReadLine();

    server.Stop();
    Console.WriteLine("Server ended ...");

    Console.ReadKey();
}
```

**Comment by moelski** [comment]
Hi !

Setting the connection to 5 or 10 reduces the load. 
But may I ask what´s the real problem for this issue? 
As I told you before I use a I7 cpu with 8 cores. And the data which is received and send back by the server is really minimal. And I can´t beleave that the routing generates so much load. And i have only one route :-)

So can you give some additional advicse how to debug this topic?
Or did you find any problemn in the code whoch causes high cpu load in special situations?

**Comment by scottoffen** [comment]
I haven't had a chance to look into this any further. The latest release (put out on 10/31) includes optimizations for content type look ups that might have been related, so you should pull that one down if you haven't already.

**Comment by scottoffen** [comment]
So, using the new performance profiling tools in VS 2015 with the latest build, I am unable to replicate any CPU spikes. I've attached my recorded diagnostic sessions for you to review, and if you see something I can improve on, let me know.

I ran two sessions using the `Grapevine.Local` project as is. The only difference between the two sessions is that in one session I had logging turned off. In both instances, I started the diagnostic session with a browser already open and I hit reload as fast as I could - several times per second, at least. Not the most scientific approach, but I figured if I saw problems there, then I would investigate further using a more rigorous method. As stated earlier, I was unable to replicate a CPU spike.

[grapevine-local-with-console-logger.diagsession.txt](https://github.com/sukona/Grapevine/files/567978/grapevine-local-with-console-logger.diagsession.txt)
[grapevine-local-with-no-logger.diagsession.txt](https://github.com/sukona/Grapevine/files/567979/grapevine-local-with-no-logger.diagsession.txt)

> Download the files and remove the `.txt` extension to view the results.

**Comment by scottoffen** [comment]
While I was not able to duplicate your exact issue, I have made some changes in how threads are handled that will likely resolve any issues you had. Those changes are in the master branch today, and will be in the next version on nuget.

**Comment by moelski** [comment]
Hi !
Just give it a try and it works like a charme. Well done!
All trouble is gone. 
Thx for your support !!!
Dominik
