### ISSUE TITLE
Documentation at https://sukona.github.io/Grapevine/ doesn't cover client use cases

### ISSUE THREAD

**Issue by Costigan** [sukona/Grapevine#146]
Hi,
  Where is documentation for RestClient?  I don't see it with the rest of the documentation, which is, I think, at https://sukona.github.io/Grapevine/.

The specific situation I got into is a NullReferenceException in RestResponse's internal constructor when I created a request without a timeout that my server failed to respond to.  The response argument was null, generating an exception a few lines into the constructor.  The NullReferenceException wasn't helpful in figuring out what I'd done wrong.

In this case, my server was crashing which had nothing to do with Grapevine, but I'm not sure how RestClient is supposed to be used.  Here's what I'm trying.  This seems verbose.  Is it what is intended?

            Client = new RestClient { Host = "localhost", Port = serverPort };
            var rq = new RestRequest("/ping");
            var rs = Client.Execute(rq);

Thanks.

**Comment by scottoffen** [comment]
Yes, that is the correct syntax. The documentation for RestClient isn't up on the project page yet, but it hasn't changed *too much* from older versions, and you can find that documentation [on the wiki](https://github.com/sukona/Grapevine/wiki/Getting-Started-RestClient-3.x).

As for a NullReferenceException, can you verify the version of Grapevine you are using, because [that bug](https://github.com/sukona/Grapevine/issues/14) should have already been fixed.

**Comment by Costigan** [comment]
In order to follow the debugger into Grapevine code, I downloaded the master branch yesterday, then added the Grapevine project to my solution.  The exception occurs on line 161 of RestResponse.cs, because response is null when passed in.  The call to RestResponse's constructor is within the catch on line 136 of RestClient.cs.  e.Response is null.  The exception prints as {"Unable to connect to the remote server"}.  The inner exception is a SocketException with this message: "No connection could be made because the target machine actively refused it 127.0.0.1:55881".  e.Status is ConnectFailure.

**Comment by scottoffen** [comment]
@Costigan I added a fix to the master branch, I'd appreciate your feedback on it before I generate a new nuget.

I've added a property on `RestClient` named `WebExceptionHandlers`. It's a dictionary of delegates with keys of type `WebExceptionStatus`. Specify a delegate for any `WebExceptionStatus` you like.

**When An Exception Is Thrown:**

- If a delegate exists for the `WebExceptionStatus`, that delegate will be invoked and the method returns null.

- If no delegate exists, then the value of the `WebException.Response` will be checked for null, and will rethrow the exception if it is.

- If there is no delegate provided and the response is not null, then a new `RestResponse` object can be instantiated and returned.

**Comment by scottoffen** [comment]
The `RequestTimeoutAction` property is now aliased to use this dictionary of delegates, but the property has been deprecated.

**Comment by Costigan** [comment]
The error message generated in the original scenario is now fine, and I think the expansion of the exceptions that users can handle makes sense, although I'm uncertain what these handlers can do that one couldn't do by catching the condition thrown back from the Execute() call.  My original question wasn't that the thrown condition was bad but that the actual condition was obscured by the NullReferenceException.  But in any case, the code is certainly fine with me as you have it.  Thank you.

**Comment by scottoffen** [comment]
Thanks. I have need for the additional exception handlers, and this looked like a good time to put them in. I'll get an updated nuget out in the next day or two.
