### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by ghost** [sukona/Grapevine#159]
Hello

Do you guys plan to add support for .NET Core?

**Comment by scottoffen** [comment]
Yes, we do.

**Comment by brookman** [comment]
Is there any news regarding .net core support? Being able to use Grapevine on UWP would be great.

**Comment by scottoffen** [comment]
It's on the road map for version 5. I expect to have a version 5 alpha out in September, and I'm targeting a late 2017 release date.

**Comment by mgtb1994** [comment]
Any news when .Net Core will be supported?

**Comment by JordanZaerr** [comment]
There is a PR that targets netstandard20 along with net4 sitting around(https://github.com/sukona/Grapevine/pull/207).  It has a test failing but it's the same test that fails on master right now because of https://github.com/sukona/Grapevine/issues/205.

**Comment by scottoffen** [comment]
Both version 4 and 5 support .NET core, only version 4 supports .NET Framework versions that aren't .netstandard compliant.
