### ISSUE TITLE
Add SendResponse Overloads for Byte Array and MemoryStream

### ISSUE THREAD

**Issue by archeg** [sukona/Grapevine#164]
Right now Grapevine only supports text responses or filestream responses. It would be nice if you could also respond with an array of bytes or memory stream (I think internally it is available, so just need to make it public)

Also I'm not sure what headers are necessary to set if you want to sent let's say image as byte array - so it would be nice if API could handle that (but this is optional as API already provides a way to set headers manually)

**Comment by scottoffen** [comment]
I like this; it's caused me to rethink the options I've provided for sending responses. Here's what I think should be done to provide the biggest bang for the buck, and allow for maximum reusability and extensibility with the least impact to the existing user base.

1. Refactor the interface - hear me out! - refactor the interface to only have *one* `SendResponse` method that takes, as it's input, a byte array.

2. Change all other `SendResponse` methods to be extensions methods on the interface that, ultimately, calls the `SendInput(ByteArray)` method. After all, they are just convenience methods anyway.

This would mean that the next guy who needs a `SendResponse` method that I don't have can easily write their own.

Thoughts? Objections? Praise?

**Comment by archeg** [comment]
Looks good. This should clear up the interface, but still providing reach functionality as before.

**Comment by scottoffen** [comment]
I have the initial work for this one up in it's own branch. I just need to double-check code coverage and then I can merge this into master.
