### ISSUE TITLE
Add proper contenttype to response for PublicFolders

### ISSUE THREAD

**Issue by sbeatz** [sukona/Grapevine#169]
is it possible to add the correct ContentType to the response when files from public folder are served

something like in [PublicFolder.cs line 149](https://github.com/sukona/Grapevine/blob/master/src/Grapevine/Server/PublicFolder.cs#L149)
if (filepath.EndsWith(".png") || filepath.EndsWith(".PNG"))
                    context.Response.ContentType = ContentType.PNG;
                else if (filepath.EndsWith(".jpeg") || filepath.EndsWith(".jpg") || filepath.EndsWith(".JPEG") || filepath.EndsWith(".JPG"))
                    context.Response.ContentType = ContentType.JPG;
                else if (filepath.EndsWith(".woff2"))
                    context.Response.ContentType = ContentType.WOFF;
                else if (filepath.EndsWith(".css"))
                    context.Response.ContentType = ContentType.CSS;
                else if (filepath.EndsWith(".ttf"))
                    context.Response.ContentType = ContentType.TTF;

as currently it is all served with a generic Contenttype

**Comment by scottoffen** [comment]
Yeah, it should do that. I'm surprised it doesn't.
