### ISSUE TITLE
Rename Payload to Body

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#170]
It may not be immediately apparent that `Payload` is a synonym for "the data in the body of the request". This could be annoying even for native English speakers, confusing for non-native English speakers and downright unusable for non-English speakers.

**Comment by wizicer** [comment]
Agree, cost me some efforts to find Payload is Body which I need.

**Comment by scottoffen** [comment]
In Grapevine 5, the `InputStream` property is exposed.
