### ISSUE TITLE
Migrate client to use HttpClient instead of HttpWebRequest

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#173]
Further investigation is required.

- [HttpClient class](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx)
- [Calling a Web API From a .NET Client](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client)
- [HttpClient Pipeline](https://www.thomaslevesque.com/2016/12/08/fun-with-the-httpclient-pipeline/)

**Comment by SoftExpert** [comment]
Hi Scott,

I found this article ([singleton-httpclient-dns](http://byterot.blogspot.fr/2016/07/singleton-httpclient-dns.html)) which highlights a lesser known side effect of using HttpClient; fortunately it provides also the solution.

Best regards,
SoftExpert

**Comment by scottoffen** [comment]
Thanks, I'll take a look at this.




Scott Offen







On Fri, Oct 13, 2017 at 6:59 AM -0600, "SoftExpert" <notifications@github.com> wrote:












Hi Scott,


I found this article (singleton-httpclient-dns) which highlights a lesser known side effect of using HttpClient; fortunately it provides also the solution.


Best regards,

SoftExpert

**Comment by scottoffen** [comment]
Grapevine 5 has the client removed in the beta. IF the client gets added again, it will be using `IHttpClient` and the `IHttpClientFactory`.
