### ISSUE TITLE
Memory Leak in Route Caching

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#175]
Remove the route caching for now as it is a potential cause for memory leaks. Will likely re-implement later when I have a better solution.

**Comment by napiro** [comment]
Hi Scott 

Your sentence implies that the caching functionality is on by default - how and where do I disable this functionality?

Thanks

**Comment by scottoffen** [comment]
It is on by default and there is now way to disable it. It will be removed in the next nuget package.
