### ISSUE TITLE
Add Extensions for JWT Token Authentication

### ISSUE THREAD

**Issue by furesoft** [sukona/Grapevine#178]
how can i add jwt token authentication?

**Comment by scottoffen** [comment]
There is currently no built in support for JWT token authentication. Support should be implemented as an extension.

**Comment by scottoffen** [comment]
I was totally wrong. This is absolutely possible, but I'd have to roll my own implementation. Working on it now.

**Comment by scottoffen** [comment]
Token creation and parsing is (for right now) up to you, but sending a receiving that token is pretty trivial. Create routes that take credentials, authenticate a user, and returns (either in the header or the body) the token you create.

You can then read the token from incoming client request headers:

```csharp
var token = context.Request.Headers.Get("Authorization");
```

and respond to invalid/expired tokens:

```csharp
if (!IsValidToken(token) // <--  you implement this
{
    context.Response.SendResponse(HttpStatusCode.Forbidden);
}
```

I'd put these in a route all by themselves and let the remaining routes rely on authentication having already occurred.

There is another project underway that will simplify this process (as well has handle much of the token generation and validation for you) for Grapevine 5.
