### ISSUE TITLE
if the querystring is 1qaz2wsx#EDC

### ISSUE THREAD

**Issue by mcheung63** [sukona/Grapevine#185]
if the GET querystring is 1qaz2wsx#EDC, var p= context.Request.QueryString["p"];, the p variable value is 1qaz2wsx, which is wrong

thanks

**Comment by scottoffen** [comment]
This is correct behavior, as the `#` is the [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) in a URI. If you want to pass the `#` in the query string, you need to [URL-encode](https://www.w3schools.com/tags/ref_urlencode.asp) the value.

**Comment by mcheung63** [comment]
super thanks
