### ISSUE TITLE
Uncaught exception in HttpResponse Can Cause Application Crash

### ISSUE THREAD

**Issue by SoftExpert** [sukona/Grapevine#188]
Hello,

The SendResponse method is writing into the OutputStream in a `try ... finally` block.
It so happens that sometimes there are network connection losses while writing the data.
OutputStream will raise an exception - and if it is not caught it will end up by crashing the whole process that launched RestServer.
For my initial tests, simply adding a `catch` in the `try ... finally` block solves the issue.
That specific request is obviously lost, but the process is not stopped any longer.
Probably adding some notification mechanism in the `catch` block would be even better.

Thank you for handling this rare case.

Best regards,
SoftExpert

**Comment by scottoffen** [comment]
I'm unable to duplicate your issue. Would you mind modifying your local copy of Grapevine to use this `try...catch...finally` block in the `SendResponse` method and let me know if it resolves your issue?

```csharp
try
{
    Response.ContentLength64 = contents.Length;
    Response.OutputStream.Write(contents, 0, contents.Length - 10);
    Response.OutputStream.Close();
}
catch
{
    Response.OutputStream.Dispose();
    throw;
}
finally
{
    Advanced.Close();
}
```

**Comment by SoftExpert** [comment]
Hi Scott,

Thank you for looking into this issue; the problem is not easily reproducible - that's the reason for which in the Gist I sent you I "simulated" an exception by changing the size of the content written in the OutputStream.
The original issue was caused by network connection loss between the Rest server and the client application, so when the server was writing the response in the OutputStream an exception has been raised.
The approach you proposed might still create issues because the exception is thrown again and the following might still happen:
1. the call stack might be lost (perhaps not according to [this](https://stackoverflow.com/questions/178456/what-is-the-proper-way-to-re-throw-an-exception-in-c) article)
2. the application running the Rest server will still be killed since an exception is thrown from SendResponse method - which is not always called within a `try ... catch` structure.

If you still think that `throw` is the way to go, then you would need to protect all SendResponse calls in the framework.

Best regards,
SoftExpert

**Comment by scottoffen** [comment]
Your second point is valid. I'll take another look at it.

**Comment by scottoffen** [comment]
There is only one place where Grapevine itself was calling the `SendResponse` method. So I added this new extension method as a last-ditch-effort to send something back to the client, and just log any exception it encounters, and modified Grapevine to call that method instead.

```csharp
public static void TrySendResponse(this IHttpResponse response, IGrapevineLogger logger, HttpStatusCode status, Exception e = null)
{
    try
    {
        response.SendResponse(status, e);
    }
    catch (Exception ex)
    {
        logger.Log(new LogEvent { Exception = ex, Level = LogLevel.Error, Message = "Failed to send response" });
    }
}
```

**Comment by SoftExpert** [comment]
Hi Scott,

Thank you for the modifications, it looks great!
There is only one issue - you inadvertently used the line I used to simulate an exception
`Response.OutputStream.Write(contents, 0, contents.Length - 10);`
which, normally, should have been 
`Response.OutputStream.Write(contents, 0, contents.Length);`

I think this is the last point to be adressed to correctly close this case.

Best regards,
SoftExpert

**Comment by scottoffen** [comment]
Corrected, thank you. Did this satisfy your test scenario?

**Comment by SoftExpert** [comment]
Hi Scott,

Thank you again!
I swear I am not picky ;-) , but I think there is still some place for an improvement [see this GIST](https://gist.github.com/SoftExpert/a443ca4b4f6d08393a632f879fe56be3).
WIth that one covered I think everything is good.

Best regards,
SoftExpert

**Comment by findusl** [comment]
Hi, 

is it correct that the fix to this issue is not yet part of the nugget which is still Version 4.1.1.0? Is there any plan to publish a new version with this issue fixed?

Best regards and keep up the good work
findusl
