### ISSUE TITLE
generate openAPI (swagger) from routing table

### ISSUE THREAD

**Issue by Xyolyp** [sukona/Grapevine#196]
I would like to be able to generate some openAPI (swagger) json from the routingtable.
I use grapevine only with method invocation and not with assembly scanning. It would be benefitial for my project to be able to provide the swagger data. It would be enough in my case if I could get the data and serve it myself.

**Comment by mristin** [comment]
Hi,
I am considering to add code generation to https://github.com/Parquery/swagger-to. @scottoffen, would you be interested to discuss a couple of approaches and design sketches?

**Comment by scottoffen** [comment]
Grapevine 5 (https://github.com/scottoffen/grapevine) is in beta, and that's the first version I'd want to implement the OpenApi with, any help anyone would like to offer in that regard would be welcome..
