### ISSUE TITLE
Mono *still* lacks support for stuff

### ISSUE THREAD

**Issue by acolomitchi** [sukona/Grapevine#201]
See #157 
<strike>Neither 4.1.0 nor 4.1.1 seem to include a fix for it.</strike>
Needs just the commenting out of the "offending" `using`, no bad effects otherwise.

<pre>/home/[snip]/development/Grapevine-4.1.1.0/src/Grapevine/Grapevine.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Server/RestServer.cs(12,60): error CS0426: The type name 'ExtendedProtectionSelector' does not exist in the type 'HttpListener</pre>

Extra:
<pre># mono --version
Mono JIT compiler version 5.14.0.177 (tarball Sat Aug  4 08:32:47 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
</pre>

**Comment by acolomitchi** [comment]
In addition:

<pre>/home/[snip]/development/Grapevine-4.1.1.0/src/Grapevine/Grapevine.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Interfaces/Server/IHttpListener.cs(135,75): error CS1061: 'HttpListener' does not contain a definition for 'DefaultServiceNames' and no extension method 'DefaultServiceNames' accepting a first argument of type 'HttpListener' could be found (are you missing a using directive or an assembly reference?)
</pre>

If you can live without, commenting out the lines gets the compilation to success.

**Comment by scottoffen** [comment]
@acolomitchi I don't have ready access to Mono to test out issues like this. Is this still an issue in the current Grapevine 4? Also, would you be so kind as to check out Grapevine 5 () and let me know if you see any Mono-related issues? It's still in beta, so if I can fix anything there before the release, that would be ideal.

**Comment by scottoffen** [comment]
I see none of this in the beta for Grapevine 5, but it looks like something are still left around in Grapevine 4. I'll clean those up and publish a new package.
