### ISSUE TITLE
An exception is encountered when the response is sent when setting Router.SendExceptionMessages = false

### ISSUE THREAD

**Issue by mattdefoor** [sukona/Grapevine#203]
While troubleshooting #202 with Grapevine 4.1.1, I ran across the following:

When **Router.SendExceptionMessages** is set to **false**, an exception is encountered at _HttpResponseExtensions.cs:48_ because the passed exception parameter is null in the call to response.SendResponse(). The parameter is not checked for a null value before it's data members are used.

` response.SendResponse($"{exception.Message}{Environment.NewLine}<br>{Environment.NewLine}{exception.StackTrace}");`

This could be changed to:

`response.SendResponse(exception != null ? $"{exception.Message}{Environment.NewLine}<br>{Environment.NewLine}{exception.StackTrace}" : string.Empty);`

This fixes the generic case where setting **Router.SendExceptionMessages = false** will cause an exception because of the null Exception parameter.

It is a temporary workaround for #202 as well, but I believe that Grapevine's response to a HEAD request with **Router.SendExceptionMessages = true** should satisfy the HEAD method spec and not return a message-body in the response.

Cheers,
Matt

**Comment by scottoffen** [comment]
@mattdefoor Can you check this with 4.1.2 and let me know if you are still experiencing this behavior?
