### ISSUE TITLE
[RestRequest] Sending binary data as payload.

### ISSUE THREAD

**Issue by stefanpavlov** [sukona/Grapevine#208]
Is there a way to upload binary data? The Payload property only works for text.

**Comment by scottoffen** [comment]
Yes, there is. I'll post some code here.

**Comment by scottoffen** [comment]
The `Payload` property reads the `InputStream` property of the the underlying [`HttpListenerRequest`](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenerrequest.inputstream?view=netframework-4.8) into a string for parsing. As long as no previous route had read this stream (it is a read-once stream), you can access this stream and read it directly.

```csharp
public static void GetBinaryData(HttpContext context)
{
    if (context.Request is HttpRequest request)
    {
        var input = request.Advanced.InputStream;
    }
}
```
