### ISSUE TITLE
[Question] When are you planning to release the next version with new updates and removing deprecated things?

### ISSUE THREAD

**Issue by sonudavidson** [sukona/Grapevine#212]
Hi,

We are interested to know when you are planning to make the next release that has new updates and the methods or properties that are marked obsolete are removed.

Please do let us know. Thanks!

**Comment by sonudavidson** [comment]
Yes, Looking forward to it! Thanks for the reply!

**Comment by scottoffen** [comment]
Version 5 is up, but still in beta.
Repository: https://github.com/scottoffen/grapevine
Documentation: https://scottoffen.github.io/grapevine/
