### ISSUE TITLE
Problem when starting RestServer from a windows service

### ISSUE THREAD

**Issue by erSitzt** [sukona/Grapevine#224]
Hi,

i'm using this Grapevine version in a windows service project an i have a little problem i dont unterstand

I'm starting the RestServer in the services OnStart like this
```
        protected override void OnStart(string[] args)
        {
            restserver = new RestServer();
            restserver.LogToConsole().Start();  // tried both with LogToConsole and without
            // more stuff after this
        }
```
Which works fine on a win 10 maschine, but does not start to listen on a win 7...
I can start the service in the foreground in which case it works on both maschines.

Service runs as networkservice account.

Any help appreciated

**Comment by scottoffen** [comment]
Is there a reason you aren't using Grapevine 5? https://github.com/scottoffen/grapevine

As far as your issue with Grapevine 4, you haven't given me enough information to assist you in this matter. Is there anything in the Event Log? Are you getting any error messages? Is this the extent of your code? I've tried this much and cannot duplicate your issue.

**Comment by erSitzt** [comment]
Grapevine 5 is dependant on .NET 5 isnt it ?
I may have to install on up to 3000 devices that are neither owned nor directly managed by us, so i try  to use a version i know to be working already, which currently is 4.6

There isnt much more to the code, it is basically a default .net windows service project which starts grapevines restserver in the onStart method

Im using only simple RestResources like the one below and everything is working fine except grapevine not listening on port 1234 when i run it as a service.
After the `restserver.Start()` im starting a rabbitmq consumer and i can verify the service is running and working, its just not listening. And i dont get any errors either.

If i start it to debug like mentioned here (https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-debug-windows-service-applications#how-to-run-a-windows-service-as-a-console-application) it works fine...

Sorry for the bad screenshot :)
![image](https://user-images.githubusercontent.com/1625376/107436985-98228980-6b2e-11eb-80a2-da3e246db8ee.png)


```
    [RestResource]
    public class TestResource
    {
        [RestRoute(HttpMethod = Grapevine.Shared.HttpMethod.GET, PathInfo = "/info")]
        public IHttpContext Info(IHttpContext context)
        {
            var info = new
            {
                hostname = "test",
                ip = "192.168.123.123",
                printers = "bla bla bla"
            };
            string json = JsonConvert.SerializeObject(info);
            string jsonFormatted = JValue.Parse(json).ToString(Formatting.Indented);

            context.Response.ContentType = Grapevine.Shared.ContentType.JSON;
            context.Response.SendResponse(jsonFormatted);
            return context;
        }
    }

**Comment by scottoffen** [comment]
> Grapevine 5 is dependent on .NET 5 isnt it?

No. Grapevine 5 targets .NET Standard 2.0, .NET Standard 2.1 **AND** .NET 5.0, so you can use Grapevine 5 as far back as .NET Framework 4.6.1.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by scottoffen** [comment]
If everything is working when you debug or don't run it as a service, then the likely culprit is that you aren't keeping the thread alive once the server starts. The `IRestServer.Start()` method doesn't block the thread.

In the link you posted, they show this sample code to "debug" the application.

```csharp
internal void TestStartupAndStop(string[] args)  
{  
    this.OnStart(args);  
    Console.ReadLine();  
    this.OnStop();  
} 
```

The line with `Console.ReadLine()` is what is keeping the thread alive while the service runs in the debugging scenario.

As of Grapevine 5.0.0-rc.6, there is an extension method [`IRestServer.Run(CancellationToken token)`](https://github.com/scottoffen/grapevine/blob/main/src/Grapevine/MiddlewareExtensions.cs#L28) that can be used instead of `IRestServer.Start()` that will block the thread to keep your background service running.

If you still want to use Grapevine 4, you just need to add this method to your project, and call it at the appropriate place.

```csharp
public static void Run(this IRestServer server, CancellationToken token)
{
    ManualResetEventSlim manualResetEvent = new ManualResetEventSlim(true);

    server.Start();
    manualResetEvent.Wait(token);
    server.Stop();
}
```

**Comment by erSitzt** [comment]
Thanks Scott, i will try that.
The weird thing is, it runs fine as a service on multiple win 10 boxes...

Im not programming c# normally... or even programming... so excuse my errors :)

**Comment by erSitzt** [comment]
I went on to install VS on that box, to attach to the service and see whats happening first..
And it worked out of the box when i build the service there...

So it seems everything is running and keeps running as expected, but somehow the builds from different systems behave differently... i guess some stupid error i made somewhere along the way :(

Thanks for your help and the great work !
