### ISSUE TITLE
Starting the RESTServer should throw an exception if anything goes wrong

### ISSUE THREAD

**Issue by reppners** [sukona/Grapevine#23]
Yesterday I had a problem which took a while to figure out:

    var server = new RESTServer();
    server.Start();

We didn't fire it up with admin privileges so the HttpListener throw an exception. We had no clue it did until we debugged inside the Grapevine start method. 

I think an exception which prevented the server start should in no case be swallowed because the user of the library is the one who has to handle this not the library itself. 

Of course there is a logger so if this is turned on at least something is visible. But how should an application relying on the server listening should handle the event where the server is NOT running because an exception was thrown?

At the very least there should be the possibility to pass an action that is executed with the exception is parameter to indicate the failure of the failed attempt to start the server. Otherwise there is no proper way for the application to handle the failure.

I also am aware of the possibility to check the `IsListening`-property but this is not giving access to the exception which I might want to have.

**Comment by scottoffen** [comment]
That was by design, so this would be an enhancement.
