### ISSUE TITLE
Error new version Google Chrome 94

### ISSUE THREAD

**Issue by elvispdosreis** [sukona/Grapevine#234]
I'm having trouble using it as the new version of Chrome with the 93.X version works perfectly

Grapevine 4.2.2

Google Chrome
Version 94.0.4606.61 (Official Version) 64-bit

```csharp
[RestRoute(HttpMethod = HttpMethod.OPTIONS)]
public IHttpContext Cors(IHttpContext context)
{
    context.Response.StatusCode = HttpStatusCode.Ok;
    context.Response.Headers["Access-Control-Allow-Methods"] = "POST, GET, PUT, OPTIONS";
    context.Response.Headers["Access-Control-Allow-Origin"] = "*";
    context.Response.Headers["Access-Control-Allow-Headers"] = "Origin, X-Requested-With, Content-Type, Authorization";
    context.Response.SendResponse("");
    return context;
}
```

![image](https://user-images.githubusercontent.com/15267623/134719805-b990fb87-a4e7-40c4-bcc2-34acad4f139d.png)

https://developer.chrome.com/blog/private-network-access-update/

does it have something to do with it this is my scenario an external site called a local api via ajax request

**Comment by scottoffen** [comment]
I don't understand the issue you are having. Can you give me more information on the expected behavior vs the actual behavior?
