### ISSUE TITLE
Grapevine won't find routes or resources located in assemblies where assembly.FullName =~ /^grapevine/i

### ISSUE THREAD

**Issue by RRM76** [sukona/Grapevine#25]
First, thanks for library.
I have lost however some time before I found some really annoying issue.

I wanted to test Grapevine library and created a project which I called... GrapevineTest. Not very original, isn't it?

When I tried to add my own code for REST incoming messages it didn't work. I used your example and it didn't work:

    [RESTRoute(Method = HttpMethod.GET)]
    public void HandleAllGetRequests(HttpListenerContext context)
    {
    this.SendTextResponse(context, "GET is a success!");
    }

After a long search  and being completely stupid why it doesn't work I found this:

    private Dictionary<string, RESTResource> LoadRestResources()
    {
    ....              
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.FullName.Matches(@"^(microsoft|mscorlib|vshost|system|grapevine)")) { continue; }

For my project assembly.FullName was GrapevineTest so the library skipped it. When I renamed my project it began to work.

Not a big problem, but I'd like to warn the others :)

**Comment by scottoffen** [comment]
Good catch.

I was going for efficiency here by not traversing assemblies I expected would both be large AND not contain the methods I was after. All of those are pretty safe bets - except the last one.

I think the only question left is: would you consider this a defect that should be fixed? I'm leaning towards "yes", but I'd like to hear your opinion.

**Comment by RRM76** [comment]
> I think the only question left is: would you consider this a defect that should be fixed? I'm leaning >towards "yes", but I'd like to hear your opinion.

Thanks for an answer.
Yes, seeing a fix would be nice. If it happened to me, it could happen to someone else too. And it shouldn't be a big work.
