### ISSUE TITLE
The I/O operation has been aborted because of either a thread exit or an application request

### ISSUE THREAD

**Issue by vmyilsamy** [sukona/Grapevine#26]
Hi, It's a great library to have slim web server on any machine.

When I try to dispose all the resources that I use including RESTServer I get the below exception

"The I/O operation has been aborted because of either a thread exit or an application request"

Just create a simple console with the below lines, please turn on the CLR exception

RESTServer server = Init(8008, "sampleapi");
            server.Start();
            Console.ReadLine();
            server.Dispose();

I tried few options before submitting this request the exception still occurs.

Many thanks

**Comment by scottoffen** [comment]
Thanks! I'm glad you are finding it useful.

Are you using the current version available (3.0.4) on [NuGet](http://www.nuget.org/packages/Grapevine/)? If not, which branch did you pull from and when?

**Comment by vmyilsamy** [comment]
Thank for the quick response.

Yes I'm using version 3.0.4 downloaded the source from GitHub.

**Comment by scottoffen** [comment]
I'm unfamiliar with the `Init` method you are using here, but I have been unable to duplicate this issues. Can you provide a different use case? This seems to work fine:

```csharp
var server = new RESTServer(port:"8008");
server.Start();

Console.WriteLine("Server is running");
Console.ReadLine();

Console.Write("Disposing of server...");
server.Dispose();

Console.WriteLine("done");
System.Console.ReadLine();
```
