### ISSUE TITLE
InternalServerError override not invoked in implementation of RESTResource

### ISSUE THREAD

**Issue by reppners** [sukona/Grapevine#27]
I tried to implement custom route exception handling by overriding the method `InternalServerError` in my implementation of `RESTResource`.

My override is never invoked when deliberately throwing an Exception in my route handler method.
I tracked the issue down to the finally block of the [ProcessRequest()](https://github.com/scottoffen/Grapevine/blob/9377a907837d8f0418687bcfc5b3adf0ba002d5e/Grapevine/Server/RESTServer.cs#L477-L490)-method.

As I see it, the methods `InternalServerError()` and `NotFound()` should be executed on `route`.

If I'm right I can provide a pull-request.

**Comment by scottoffen** [comment]
The mechanism for this is completely different in 4.0, will not fix in 3.x
