### ISSUE TITLE
PathInfo return matches as parameters?

### ISSUE THREAD

**Issue by tekhedd** [sukona/Grapevine#29]
I find myself re-matching path parts in my handlers. I am considering modifying the RESTServer to pass any matches from its regex match (PathInfo) as an optional extra parameter to the handler. Does this seem desirable?

The more complicated part of this is backward compatibilty, so it would need to detect the method signature, as I am pretty sure Invoke() will barf if the array size does not match the invoked method signature. 

The obvious solution is something like like void MyGetHandler( HttpListenerContext ctx, string [] matches ) or similar. Other options include:
 1) a variable number of string parameters, but that prevents any future additions
 2) dictionary of values, using named regex match patterns (does RegEx support this?)
 3) not bothering at all

Just a thought. it just irks me to write my patterns twice. It also irks me to see 50-odd regex patterns recompiled on every http request, but that's for another issue I guess. :)

Here is an example: most of my handlers look like this:

      static readonly Regex GetSomethingStatusParams = 
         new Regex( @"^/api/something/(?<id>[^/]*)/status" );

      [RESTRoute(Method = HttpMethod.GET, 
                 PathInfo = @"^/api/something/([^/]*)/status$")]
      public void HttpGetSomethingStatus( HttpListenerContext ctx )
      {
         // UrlMatcher throws rest specific exceptions on failure for convenience...
         UrlMatcher matcher = new UrlMatcher( GetSomethingStatusParams, ctx.Request.RawUrl );
         SendJsonResponse( ctx, GetSomethingStatus( matcher.GetLong( "id" ) ) );
      }

Which is a bit cumbersome. The Server could, say, check whether (MethodInfo.Parameters.Length > 1), and if so, pass the match from the regex into the function, leading to something along the lines of:

      [RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/api/something/(<id>[^/]*)/status$")]
      public void HttpGetSomethingStatus( HttpListenerContext ctx, Match urlMatch )
      {
         long id = _ConvertToLong( urlMatch.Groups["id"].Value );
         SendJsonResponse( ctx, GetSomethingStatus( id );

Should be doable, prevents multiply-typing patterns, etc. Desirable?

...Another quick update: I have implemented this--it's pretty simple really. I want to clean up the implementation and add tests (how do I run these on mono!?). Also I made it against GrapevinePlus (oops) and need to.. backport? upport? sideport it? It would be pretty simple to do magic "name matching" like WebApi and other apis do, but personally I think just returning the matching Match is more flexible, simple, and fits with the whole "simple" approach of Grapevine.

**Comment by tekhedd** [comment]
Submitted a PR for comment as scottoffen/Grapevine#30

**Comment by scottoffen** [comment]
> it seems like the entire route discovery/cache/lookup should be moved out of RESTServer into a separate class

I totally agree. I'm working that into 4.0. 3.1 is bug fixes.

**Comment by scottoffen** [comment]
Completed in dev for 4.0
