### ISSUE TITLE
EventLogger.ExceptionToString error when exception.Message == null

### ISSUE THREAD

**Issue by tekhedd** [sukona/Grapevine#31]
title is wrong (can I change that?) there is an exception but Message is not the issue. Not sure why ExceptionToString is throwing, but you wouldn't think it would, would you?

[update] ExceptionToString is throwing because trace.GetFrame(2) is returning null. Because the stack isn't that deep. :) 

Proposal 2 still valid: in RESTServer.ProcessRequest, wrap the finally{} block's error handler in a try/finally block to ensure that ctx.Response.Close() and ctx.Close() are always called out of paranoia. (In fact may want to add a second block around the whole function.) Also might want a top level exception handler that tries to use Close(byte[]) to send a generic "something is dreadfully wrong" response.

**Comment by scottoffen** [comment]
Have you already merged something in for this one?
