### ISSUE TITLE
Static file expire time is usually in the past

### ISSUE THREAD

**Issue by tekhedd** [sukona/Grapevine#32]
expireDate = "last write time" + 23 hours. What you probably want is DateTime.Now + 23 hours. Expires is dependent on the system clock being correct and probably a bad choice, unless also combined with max-age and used maily for backward compatibility.

I would probably change it to "max-age": age + 86400 (1d), leaving the Last-Modified exactly as it is and removing Expires or changing it to be relative to DateTime.Now.

            var lastWriteTime = File.GetLastWriteTimeUtc(path);
            var lastModified = lastWriteTime.ToString("R");
            var maxAge = (long)((DateTime.UtcNow - lastWriteTime).TotalSeconds + 86400);

**Comment by scottoffen** [comment]
For now, I'm going to update this to use now + 23 hours, but I'd like to revisit this in the future so that we have both reasonable defaults and simple ways to modify the value.
