### ISSUE TITLE
System.ArgumentNullException if host ist not reachable

### ISSUE THREAD

**Issue by Beluk** [sukona/Grapevine#36]
If the host is not reachable the following lines result in an ArgumentNullException:

            var client = new RESTClient("http://localhost:4444");
            var request = new RESTRequest("test");
            var response = client.Execute(request);

The Message itself says: The value must not be null. Paramater name: cookies

The error is misleading, it should say that the host was not reachable.

**Comment by scottoffen** [comment]
Fixed
