### ISSUE TITLE
Implement thread-safe RestServer.Stop() for use in routes

### ISSUE THREAD

**Issue by hwacookie** [sukona/Grapevine#40]
Ok, this might rather be a issue in the documentation than in the code, but anyway ...

Using the suggested ...

```c#
[RESTRoute(Method = HttpMethod.DELETE, PathInfo = @"^/shutdown$")]
public void HandleShutDownRequests(HttpListenerContext context)
{
    this.SendTextResponse(context, "shutting down");
    this.Server.Stop();
}
```
to remotely shutdown the Server does not work for me. If I use it as suggested, I get a deadlock in the RestServer.Stop() method, which does not surprise me because of the 

```c#
foreach (Thread worker in this._workers)
{
    worker.Join();
}
```
that can be found there. The RESTRoute that invoked the stop uses one of these workers, doesn't it?

So, I'm using this instead:

```c#
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/exit$")]
public void HandleShutDownRequests(HttpListenerContext context)
{
    this.SendTextResponse(context, "shutting down");
    // create a new thread that will kill the server asynchronously
    (new Thread(() => Server.Stop() )).Start();
}
```

PS: Thanks for making this available!

**Comment by scottoffen** [comment]
At the very least I'll update the documentation with this.
