### ISSUE TITLE
RestServer Authentication

### ISSUE THREAD

**Issue by drdran** [sukona/Grapevine#42]
How to implement a basic auth system in the RestServer?

**Comment by scottoffen** [comment]
**3.1.0 And Lower**

I don't think there was an easy way to do this in 3.x and earlier versions short of having every route make a call to some custom authentication class, passing in the http context.

**4.0.0 and Higher**

4.0 introduces a router and a routing table, allowing multiple methods to handle incoming requests in the order that the methods were registered with the router - very much inspired by [Express](http://expressjs.com/). This will make things like authentication (and other middleware) very easy to use.

Given this, you can expect to see more projects here to support common middleware requirements.

There is an alpha of 4.0 up on [nuget.org](https://www.nuget.org/packages/Grapevine/) now that you can pull down and start to play with.
