### ISSUE TITLE
Creating a cluster with multiple RESTServers does not process HTTP requests

### ISSUE THREAD

**Issue by DarriusWrightGD** [sukona/Grapevine#43]
[RESTScope(BaseUrl = "http://localhost:1111")]
    public sealed class ResourceD : RESTResource
    {
        [RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/resource/d")]
        public void MyGetResponder(HttpListenerContext context)
        {
            this.SendTextResponse(context, "Resource D limited to http://localhost:1111");
        }
    }

    [RESTScope(BaseUrl = "http://localhost:2222")]
    public sealed class ResourceE : RESTResource
    {
        [RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/resource/e$")]
        public void MyGetResponder(HttpListenerContext context)
        {
            this.SendTextResponse(context, "Resource E limited to http://localhost:2222");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var cluster = new RESTCluster();
            cluster.Add("A", new RESTServer {Port= "1111"});
            cluster.Add("B", new RESTServer {Port= "2222"});

            cluster.StartAll();
  
            Console.WriteLine("Press Enter to continue");
            Console.ReadLine();
            cluster.StopAll();
        }
    }

**Comment by scottoffen** [comment]
Looks like I'll be doing a 3.1.1...
:(
