### ISSUE TITLE
Passing application-specific info to response handlers

### ISSUE THREAD

**Issue by Costigan** [sukona/Grapevine#44]
What is the appropriate way to communicate application-specific information from the program that starts the server to the request handlers?  I'm currently putting that information into static properties of the sealed class that derives from RESTResource, because, unless I've missed it, the program that starts the server has no control over the lifecyle of the instance(s) of that class that are created by the server.  Static properties suffice for now, but that approach could complicate things if one needs to start multiple servers.  Would you consider allowing user code to instantiate these instances and pass them to the server in the configuration object?

**Comment by scottoffen** [comment]
This idea is intriguing. Can you provide some concrete examples?

**Comment by scottoffen** [comment]
I think the method you've described for use In 3.x is sufficient. As I'm working now on 4.0, I'm open to implementing a feature like this, but I'd need more information from @Costigan to make sure I'm hitting your use case.

In 4.0, the IHttpContext that is passed into every route has a `.Dynamic` property of type ExpandoObject - the real question is how to get application data in there before it gets sent to the route. Unlike previous versions, 4.0 uses a routing table, and you can map multiple methods to the same http request in much the same way as Express middleware. As long as one of the first routes you add to the routing table hits all the Http Method/PathInfo patterns you want it to you can add information to that `.Dynamic` object before anything other route sees it.

**Comment by Costigan** [comment]
Sorry for commenting and then disappearing for a while.

I think my use case is likely to be a common one.  My REST server will relay requests to a database and format the responses.  In my specific case, it's a database of spacecraft telemetry packets, but it's still just a database.

So, my original question is this (and I probably should have stated it this way):

1. Where are users of Grapevine intended to store database connections, and
2. How does one manage the connection's lifecycle (starting, stopping, restarting)?

My confusion stemmed from the fact that there's no direct connection between the RESTServer instance and the RESTResource instances (rather, sealed subclasses of).

I control the lifecycle of the RESTServer instance, so I can easily create, start and stop my database connection at the appropriate times.

I do not control the lifecycles of the RESTResource instances, so associating the database connection lifecycle with one of them won't work.  (Although I could use constructors and finalizers to start and stop database connections such that a connection would be available during the handling of any route, the framework makes no guarantees about when and how many of these sealed instances will be created.  Grapevine could create the minimal number needed to cover all declared route patterns and keep them all until the server shuts down, or it could create a new one for each response, or anything in between.)  Since a user has no control over the lifecycle of these instances, then their instance variables are not really options for holding application state.

What you describe for 4.x would be fine for my use case.  I think it would be better for users to be able to pass an ExpandoObject to the server as a property of the ServerOptions instance for my case than to force all route handlers to check the ExpandoObject and get it set up if it hasn't been yet.  Getting that object back as a property of the server context is fine.
 - Costigan

**Comment by scottoffen** [comment]
This is certainly a common one use case. Off the top of my head, here is how I would have gone about managing this - but I'm open to the possibility of there being a better way.

- A database connection pools id controlled by a singleton, instantiated on server start using `OnBeforeStart()` or `OnAfterStart()`.
- In 3.x - where one request executed only one method - the singleton provides a database connection from the pool on demand to the method that requires it. The method disposes of it before the method completes.
- In 4.x, one of the first routes added - and it might need to match on every `HttpMethod` and `PathInfo` - acquires a connection from the pool and assigns it to a property of the `Dynamic` property on the `HttpContext`. Database calls are made throughout the route. When routing completes - which may happen before all routes are executed, depending on how you set them up - and the `HttpContext` instances is disposed of, the connection should be released.
- The database connection pool is disposed of on server stop using `OnBeforeStop()` or `OnAfterStop()`.

Likewise, the new route creation mechanism is intended to provide additional control over the RestResource instances used during routing. I'm working on the documentation for that now, it should be available in the next week or two.

**Comment by Costigan** [comment]
Thank you for your reply.

The solution you describe for version 3.x is functionally equivalent to what I did, although what you've described is clearer (i.e., better).  The singleton pattern in c# generally relies on storing the single instance as a static variable on some class.  I just initialized that static variable with my 'connection' in my Main() before starting the server and closed it in the Main() after the server exited.  I didn't implement the singleton pattern explicitly, but there was just one connection.

How does this generalize to support RESTClusters?

Your example would extend easily, but that's because the connections in the pool are equivalent ... they all connect to the same database with the same connection parameters ... and the pool is really about getting and managing concurrency.

My use case is a little different.  I want to map each REST server to a separate database.

(I'm using an in-process database.  What I'm calling a 'connection' is an object whose interface implements various query methods.  It's thread safe and handles concurrency inside.  So this object is analogous to the singleton in your approach.  In my use case, multiple instances of the database can exist within one .NET process.  I use one database instance to manage each set of telemetry.)

Back to RESTClusters.  I want have distinct REST services, on distinct ports, for several sets of telemetry.  How would I do that?

Following your solution for version 3.x, I could have the singleton object hold a dictionary that maps some key, say the port # for simplicity, to  distinct database interface objects.  Every handler method would have a RESTScope declaration with the port # and that same port statically in the code.  The method would fetch the singleton, fetch the dictionary, give it the port # and receive the database interface.

This would work, but the combination of the singleton and the dictionary feels clunky to me.  Used together, they say that I didn't really want a single object.  I really wanted to associate one database interface object with each RESTServer that I created, but there wasn't a good way to do that.  There's no way to walk back from inside the handler to the server, and there's no way to attach the database interface to the server itself. (I could subclass RESTServer, since it isn't sealed, add an instance variable, and store it there, but that's a lot of machinery just to attach it.)

I get that there's no simple relationship between the handlers and the servers, and so, if I understand things, you didn't provide a way to walk back from handler to server in 3.x.

I don't follow your solution for 4.x.  I haven't read the Grapevine code thoroughly.  Is HttpContext a new wrapper for HttpListenerContext objects?  (The bit of reading I have done indicates that HttpContext is that and that it will allow the handler to get to the server, which is nice.)  If the server object had a .Dynamic property, I could store things there.

I'm less clear on how the .Dynamic property of HttpContext instances would work, because I don't understand when HttpContext instances are created and how many there might be.  Suppose I had the simplest case of a single hander in my application, and it was handling a request.  During that, it assigned some value to some property of the HttpContext's .Dynamic property.  What guarantee would I have that the next call to the same handler would see that same HttpContext instance and, therefore, that assignment?

Finally, I am curious about your decision to use attributes to associate route information with handler functions.  I'm sure you considered alternatives.  What were they?

Attributes make this association syntactically nice.  They're clear, and they're probably a great choice for almost all situations.

They are, however, static.  An alternative would be to use lambdas for handlers and provide a method for registering them with your framework before starting any servers.  This registration method would accept the lambda expression and the same routing information that the attributes currently do.  There wouldn't be any searching of assemblies.  Lambdas could be stored in a variable and registered multiple times with different routing info.  They could be closed over variables in a containing scope so that they could have or share state (equivalent to instance variables on RESTResource child classes).  You wouldn't be able to provide helper methods as easily, because there would be no RESTResource class to provide them, but perhaps you could provide equivalent methods accessible through the HttpContext objects.  The set of handlers that gets registered with your framework could be then determined at runtime, depending on configuration files, command line arguments or whatever.

This last idea is a version of the idea in my first comment that I think is what you thought was intriguing.  That idea was to associate handlers with servers by providing them as methods on RESTResouce subclasses (as you designed) and them with servers by instantiating those subclasses and passing that them to the server or servers that will use them.  Having the user do this explicitly makes the lifecycle of these objects clear (it currently isn't, to me at least).  Having the lifecycle of those instances clear makes initialization of instance variables on those instances (which are shared between handlers) also clear.  Absent that, if you put an instance variable in your RESTResource subclass so that it provides state for handlers, it's unclear how many times that instance variable will be initialized.  (I really mean it's unclear how many instances of the subclass will be created, each one initializing its instance variables once, of course.  That's why I couldn't have put my database interface there.  I could have put it on a static variable of that class, but that's just equivalent to the singleton and requires a dictionary to deal with multiple servers.)

Instead, you've associated RESTResources (which are sets of handlers) with servers by:
a. Providing RESTScope declarations, and
b. Providing Host, port and Protocol fields in ServerOptions that go to RESTServer's.

It is a little odd that these aren't connected.  That is, if I want to have a server on port 7777 and another on 8888 with distinct routes for each, I have to declare the BaseUrl's and then separately start two servers with ServerOptions that match the BaseUrls.  I assume these aren't checked against each other.  Is that right?  If I mess one up, is there any indication of that?

One could imagine your code collecting all of the RESTScope declarations and figuring out how many servers need to be run and with what protocols, hostnames and ports.
Or one could imagine passing the RESTResource objects (associated with the RESTScopes) to the servers.  Either way, the protocol/hostname/port's are declared only once.

(Regarding the first option, I do know that there are other things that your servers are doing (OnStart, et al, WebRoot, Connections ...) but the attributes are so central, those other things might have been handled in another way.)

Anyway, I'm rambling.  The solution you suggest for version 3.x will work for me.  I can extend it to use a dictionary when I have multiple servers or subclass RESTServer.
I don't understand key parts of your solution for 4.x, but the solution for 3.x would still work.  So my original question was well-answered.  Thank you.

**Comment by scottoffen** [comment]
> An alternative would be to use lambdas for handlers and provide a method for registering them with your framework before starting any servers. This registration method would accept the lambda expression and the same routing information that the attributes currently do. There wouldn't be any searching of assemblies. Lambdas could be stored in a variable and registered multiple times with different routing info. They could be closed over variables in a containing scope so that they could have or share state (equivalent to instance variables on RESTResource child classes).

This exactly describes the current functionality of 4.x. Once the documentation is all up, we can have another conversation about it all fits together - mostly to see if there isn't a better way to handle some of the specific scenarios you've described.

Meanwhile, the Dynamic property on `HttpContext` (which is, indeed, a convenience wrapper for HttpListenerContext), `HttpRequest` and `HttpResource` is applied via an abstract class, so adding it to the `RestServer` class is trivial. I'll get that into the next alpha. (See issue #57).

Also, thank you for sharing how you are using Grapevine. That really helps with figuring out what new features I might need to add in the future and their priorities.
