### ISSUE TITLE
How to Implement Windows Authentication

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#88]
Write up a tutorial on how to do this, put on github.io page.

**Comment by drdran** [comment]
Hi do you have some update of that issue?

If you need some tester, prease tell me something.

Regards

Franco

**Comment by scottoffen** [comment]
I don't have an update. This is just a documentation task. Given that `RestServer` wraps `HttpListener`, you can look up information on how to do this with `HttpListener` and it should be pretty easy to figure out how to modify that process for Grapevine.
