### ISSUE TITLE
Limit the number of pending requests

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#98]
Accept requests immediately and return 500 if the server is too busy.

**Comment by stevelong00** [comment]
I just implemented this in a fork, would you like me to open a pull request?

**Comment by scottoffen** [comment]
Yeah, sure. I was just toying around with the idea - so far, no one has requested this - but I'd be interested in an implementation.

**Comment by scottoffen** [comment]
I just took a look at your implementation. It's pretty straightforward, similar (conceptually) to what I was thinking about. Do you have any way of asserting that it works?

**Comment by scottoffen** [comment]
After reviewing your implementation, I think I'd rather move the logic out of `RestServer` class, and instead implement something it like this:

```csharp
public static class ThreadPoolManager
{
    public static int GetMaxAvailableThreads()
    {
        int maxWorkerThreads;
        int maxIoThreads;
        ThreadPool.GetMaxThreads(out maxWorkerThreads, out maxIoThreads);

        return maxWorkerThreads;
    }

    public static void SetMaxAvailableThreads(int threadCount)
    {
        int maxWorkerThreads;
        int maxIoThreads;
        ThreadPool.GetMaxThreads(out maxWorkerThreads, out maxIoThreads);

        int minWorkerThreads;
        int minIoThreads;
        ThreadPool.GetMinThreads(out minWorkerThreads, out minIoThreads);

        ThreadPool.SetMaxThreads(threadCount <= minWorkerThreads ? minWorkerThreads : threadCount, maxIoThreads);
    }

    public static bool HasAvailableThreads()
    {
        int availableWorkerThreads;
        int availableIoThreads;
        ThreadPool.GetAvailableThreads(out availableWorkerThreads, out availableIoThreads);

        return availableIoThreads > 0;
    }
}
```

And then the property can be as simple at this:

```csharp
public int Connections
{
    get { return ThreadPoolManager.GetMaxAvailableThreads(); }
    set { ThreadPoolManager.SetMaxAvailableThreads(value); }
}
```

And in the `RestServer.ContextReady` method:

```csharp
if (!ThreadPoolManager.HasAvailableThreads())
{
    context.Response.SendResponse(HttpStatusCode.ServiceUnavailable, "");
}
else
{
    ThreadPool.QueueUserWorkItem(Router.Route, context);
}
```

But I think I'd also like a toggle around this behavior, so that it has to be enabled intentionally.

**Comment by scottoffen** [comment]
@stevelong00 Have you found this to be useful? Grapevine 5 is in beta (https://github.com/scottoffen/grapevine), and I'm debating whether or not to pull this feature in. Thoughts?
